spring:
  banner:
    location: classpath:company/banner.txt
  application:
    name: pico-company
  session:
    store-type: NONE
  messages:
    basename: company-messages
    encoding: UTF-8
  datasource:
    name: company-datasource
    url: ${COMPANY_DATASOURCE_URL:${DATASOURCE_URL:jdbc:p6spy:hsqldb:mem:company}}
    driver-class-name: ${COMPANY_DATASOURCE_DRIVER_CLASS_NAME:${DATASOURCE_DRIVER_CLASS_NAME:com.p6spy.engine.spy.P6SpyDriver}}
    username: ${COMPANY_DATASOURCE_USERNAME:${DATASOURCE_USERNAME:as}}
    password: ${COMPANY_DATASOURCE_PASSWORD:${DATASOURCE_PASSWORD:null}}
    hikari:
      maximum-pool-size: 4
  flyway:
    enabled: false
  jpa:
    database: HSQL
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        memcached:
          servers: ${HIBERNATE_MEMCACHED_SERVERS}
          username: ${HIBERNATE_MEMCACHED_USERNAME}
          password: ${HIBERNATE_MEMCACHED_PASSWORD}
        generate_statistics: false
        cache:
          use_minimal_puts: false
          use_second_level_cache: ${HIBERNATE_SECOND_LEVEL_CACHE:false}
          use_query_cache: ${HIBERNATE_QUERY_CACHE:false}
          region_prefix: ${REGION_PREFIX:}company
          default_cache_concurrency_strategy: read-write
          region:
            factory_class: com.mc.hibernate.memcached.MemcachedRegionFactory
  activemq:
    broker-url: ${ACTIVE_MQ_BROKER_URL:vm://embedded?brokerConfig=xbean:embedded-activemq.xml}
    user: ${ACTIVE_MQ_USER:}
    password: ${ACTIVE_MQ_PASSWORD:}
    in-memory: ${ACTIVE_MQ_IN_MEMORY:true}
    non-blocking-redelivery: false
    packages:
      trust-all: false
      trusted: pico.erp
    pool:
      block-if-full: true
      block-if-full-timeout: -1
      create-connection-on-startup: true
      enabled: false
      expiry-timeout: 0
      idle-timeout: 30000
      max-connections: 1
      maximum-active-session-per-connection: 100
      reconnect-on-exception: true
      time-between-expiration-check: -1
      use-anonymous-producers: false

  jms:
    listener:
      acknowledge-mode: auto
      auto-startup: true
      concurrency: 1
      max-concurrency: 1
    pub-sub-domain: false
    template:
      default-destination:
      delivery-mode: non_persistent
      priority: 100
      qos-enabled: false
      receive-timeout: 1000
      time-to-live: 36000

logging:
  level:
    org:
      springframework: INFO

owner:
  id: ${COMPANY_OWNER_ID:OWNER}
  name: ${COMPANY_OWNER_NAME:내회사}
  registrationNumber: ${COMPANY_OWNER_REGISTRATION_NUMBER:0000000000}
  representative: ${COMPANY_OWNER_REPRESENTATIVE:대표자}
  enabled: true
  address:
    id: company-owner-address
    company-id: ${COMPANY_OWNER_ID:OWNER}
    name: 분당사무실
    telephoneNumber: ${COMPANY_OWNER_TELEPHONE_NUMBER:+821011111111}
    faxNumber: ${COMPANY_OWNER_FAX_NUMBER:+821011111111}
    enabled: true
    represented: true
    address:
      postalCode: ${COMPANY_OWNER_ADDRESS_POSTAL_CODE:13496}
      street: ${COMPANY_OWNER_ADDRESS_STREET:경기도 성남시 분당구 장미로 42}
      detail: ${COMPANY_OWNER_ADDRESS_DETAIL:야탑리더스 410호}


